### PR TITLE
Essential Ubuntu Desktop Pull requests combined

### PR DESCRIPTION
**Pull request by tknerr**
This PR is simply combines the below PRs and adds them on a single branch. I consider these essential in order to get a usable Ubuntu 16.04 / 16.10 Desktop box:

 * https://github.com/boxcutter/ubuntu/pull/104 - update to Ubuntu 16.04.2
 * https://github.com/boxcutter/ubuntu/pull/103 - propagate locale to virtualbox and parallels too
 * https://github.com/boxcutter/ubuntu/pull/108 - disable periodic updates
 * https://github.com/boxcutter/ubuntu/pull/107 - install open-vm-tools-desktop

A box for testing has been published as [tknerr/ubuntu1604-desktop v2.0.27.1](https://atlas.hashicorp.com/tknerr/boxes/ubuntu1604-desktop/versions/2.0.27.1)

This PR is mainly meant to support testing this combined set of features. Up to @annawake whether to merge this big blog or the original PRs individually.

/cc @rexut @richardxia

### CODE REVIEW

**Comment by dragon788** [comment]
Would love to see this get merged. I end up having to change the locale from `en_US` to `en_US UTF-8` in `/etc/locale.gen` and run `sudo locale-gen` and reboot every time I bring up the desktop variants to get Terminal and other apps working without crashing.

**Comment by tknerr** [comment]
@dragon788 which ubuntu desktop version / provider do you still have the locale issues with? was it with a box built from this PR?

**Comment by napcs** [comment]
I would love to see this merged. Right now I'm building this locally, but it would be great if images pulled from Atlas had these fixes done - for the last six months, I've not been able to use the version there because Terminal won't open.

Is there some way I can help, other than by saying I've tested this PR as well as the individual ones over the last month or so and they work for me? :)

**Comment by dragon788** [comment]
@tknerr no issues with the PR, the last couple of times I've forgotten that the boxcutter/ubuntu-1604-desktop builds are broken and I do a `vagrant init` using them and then I spend 5-10 minutes remembering what I need to do in order to fix the terminal and `vagrant reload` again to get the window manager using the same locale settings as everything else.

**Pull request closed without merging**
