### PR TITLE
Localise boot command

### PR DESCRIPTION
**Pull request by neilkidd**
Hi - thanks for the excellent work. A breeze to get working.

A constant "itch" with prebuilt boxes is that they are all US centric. Looking into the ubuntu.json file, some of the work had already been done in the vmware builder.

I have simply extended it, extracted the values to variables and made all of the builders consistent.
I only ran the tests on virtualbox as that's what I have installed.

Hope it helps,
Regards Neil.

### CODE REVIEW

**Comment by tknerr** [comment]
@neilkidd I just tried this branch with:
```
packer build -only=virtualbox-iso -var-file=ubuntu1604-desktop.json -var "version=2.0.27.1" -var "kbd_chooser_method=de" -var "keyboard_configuration_layout=German" -var "keyboard_configuration_variant=German" ubuntu.json
```
...but it still had the US keyboard layout configured.

Any ideas what could be wrong here?

UPDATE: I'm stupid, or it's just way too late. Let me try with "Germany" instead of "German"...

**Comment by tknerr** [comment]
Tried again with:
```
packer build -only=virtualbox-iso -var-file=ubuntu1604-desktop.json -var "version=2.0.27.1" -var "kbd_chooser_method=de" -var "keyboard_configuration_layout=Germany" -var "keyboard_configuration_variant=Germany" ubuntu.json
```

But the keyboard still has the US layout after starting the VM.

Output from `debconf-get-selections | grep keyboard`:
``` 

```
vagrant@linus-kitchen:~$ debconf-get-selections | grep keyboard
debconf: DbDriver "passwords" warning: could not open /var/cache/debconf/passwords.dat: Permission denied
d-i	keyboard-configuration/toggle	select	Alt+Shift
keyboard-configuration	keyboard-configuration/toggle	select	Alt+Shift
d-i	keyboard-configuration/xkb-keymap	select	
keyboard-configuration	keyboard-configuration/xkb-keymap	select	
# Detecting your keyboard layout
keyboard-configuration	console-setup/detect	detect-keyboard	
keyboard-configuration	console-setup/detected	note	
# Keep default keyboard layout ()?
d-i	keyboard-configuration/unsupported_layout	boolean	true
keyboard-configuration	keyboard-configuration/unsupported_layout	boolean	true
# Choices: The default for the keyboard layout, No AltGr key, Right Alt (AltGr), Right Control, Right Logo key, Menu key, Left Alt, Left Logo key, Keypad Enter key, Both Logo keys, Both Alt keys
d-i	keyboard-configuration/altgr	select	The default for the keyboard layout
keyboard-configuration	keyboard-configuration/altgr	select	The default for the keyboard layout
# Keep default keyboard options ()?
d-i	keyboard-configuration/unsupported_options	boolean	true
keyboard-configuration	keyboard-configuration/unsupported_options	boolean	true
d-i	keyboard-configuration/ctrl_alt_bksp	boolean	false
keyboard-configuration	keyboard-configuration/ctrl_alt_bksp	boolean	false
d-i	keyboard-configuration/variantcode	string	
keyboard-configuration	keyboard-configuration/variantcode	string	
d-i	keyboard-configuration/variant	select	Germany
keyboard-configuration	keyboard-configuration/variant	select	Germany
# Keep current keyboard options in the configuration file?
d-i	keyboard-configuration/unsupported_config_options	boolean	true
keyboard-configuration	keyboard-configuration/unsupported_config_options	boolean	true
# Choices: A4Tech KB-21, A4Tech KBS-8, A4Tech Wireless Desktop RFKB-23, Acer AirKey V, Acer C300, Acer Ferrari 4000, Acer Laptop, Advance Scorpius KI, Amiga, Apple, Apple Aluminium Keyboard (ANSI), Apple Aluminium Keyboard (ISO), Apple Aluminium Keyboard (JIS), Apple Laptop, Asus Laptop, Atari TT, Azona RF2300 wireless Internet Keyboard, BenQ X-Touch, BenQ X-Touch 730, BenQ X-Touch 800, Brother Internet Keyboard, BTC 5090, BTC 5113RF Multimedia, BTC 5126T, BTC 6301URF, BTC 9000, BTC 9000A, BTC 9001AH, BTC 9019U, BTC 9116U Mini Wireless Internet and Gaming, Cherry Blue Line CyBo@rd, Cherry Blue Line CyBo@rd (alternate option), Cherry B.UNLIMITED, Cherry CyBo@rd USB-Hub, Cherry CyMotion Expert, Cherry CyMotion Master Linux, Cherry CyMotion Master XPress, Chicony Internet Keyboard, Chicony KB-9885, Chicony KU-0108, Chicony KU-0420, Classmate PC, Compaq Easy Access Keyboard, Compaq Internet Keyboard (13 keys), Compaq Internet Keyboard (18 keys), Compaq Internet Keyboard (7 keys), Compaq iPaq Keyboard, Creative Desktop Wireless 7000, Dell, Dell 101-key PC, Dell Laptop/notebook Inspiron 6xxx/8xxx, Dell Laptop/notebook Precision M series, Dell Latitude series laptop, Dell Precision M65, Dell SK-8125, Dell SK-8135, Dell USB Multimedia Keyboard, Dexxa Wireless Desktop Keyboard, Diamond 9801 / 9802 series, Do not configure keyboard; keep kernel keymap, DTK2000, Ennyah DKB-1008, Everex STEPnote, FL90, Fujitsu-Siemens Computers AMILO laptop, Generic 101-key PC, Generic 102-key (Intl) PC, Generic 104-key PC, Generic 105-key (Intl) PC, Genius Comfy KB-12e, Genius Comfy KB-16M / Genius MM Keyboard KWD-910, Genius Comfy KB-21e-Scroll, Genius KB-19e NB, Genius KKB-2050HS, Gyration, Happy Hacking Keyboard, Happy Hacking Keyboard for Mac, Hewlett-Packard Internet Keyboard, Hewlett-Packard Mini 110 Notebook, Hewlett-Packard nx9020, Hewlett-Packard Omnibook 500 FA, Hewlett-Packard Omnibook 5xx, Hewlett-Packard Omnibook 6000/6100, Hewlett-Packard Omnibook XE3 GC, Hewlett-Packard Omnibook XE3 GF, Hewlett-Packard Omnibook XT1000, Hewlett-Packard Pavilion dv5, Hewlett-Packard Pavilion ZT11xx, Hewlett-Packard SK-250x Multimedia Keyboard, Honeywell Euroboard, HTC Dream, Htc Dream phone, IBM Rapid Access, IBM Rapid Access II, IBM Space Saver, IBM ThinkPad 560Z/600/600E/A22E, IBM ThinkPad R60/T60/R61/T61, IBM ThinkPad Z60m/Z60t/Z61m/Z61t, Keytronic FlexPro, Kinesis, Laptop/notebook Compaq (eg. Armada) Laptop Keyboard, Laptop/notebook Compaq (eg. Presario) Internet Keyboard, Laptop/notebook eMachines m68xx, Logitech Access Keyboard, Logitech Cordless Desktop, Logitech Cordless Desktop (alternate option), Logitech Cordless Desktop EX110, Logitech Cordless Desktop iTouch, Logitech Cordless Desktop LX-300, Logitech Cordless Desktop Navigator, Logitech Cordless Desktop Optical, Logitech Cordless Desktop Pro (alternate option 2), Logitech Cordless Freedom/Desktop Navigator, Logitech diNovo Edge Keyboard, Logitech diNovo Keyboard, Logitech G15 extra keys via G15daemon, Logitech Generic Keyboard, Logitech Internet 350 Keyboard, Logitech Internet Keyboard, Logitech Internet Navigator Keyboard, Logitech iTouch, Logitech iTouch Cordless Keyboard (model Y-RB6), Logitech iTouch Internet Navigator Keyboard SE, Logitech iTouch Internet Navigator Keyboard SE (USB), Logitech Media Elite Keyboard, Logitech Ultra-X Cordless Media Desktop Keyboard, Logitech Ultra-X Keyboard, MacBook/MacBook Pro, MacBook/MacBook Pro (Intl), Macintosh, Macintosh Old, Memorex MX1998, Memorex MX2500 EZ-Access Keyboard, Memorex MX2750, Microsoft Comfort Curve Keyboard 2000, Microsoft Internet Keyboard, Microsoft Internet Keyboard Pro\, Swedish, Microsoft Natural, Microsoft Natural Ergonomic Keyboard 4000, Microsoft Natural Keyboard Elite, Microsoft Natural Keyboard Pro OEM, Microsoft Natural Keyboard Pro / Microsoft Internet Keyboard Pro, Microsoft Natural Keyboard Pro USB / Microsoft Internet Keyboard Pro, Microsoft Natural Wireless Ergonomic Keyboard 7000, Microsoft Office Keyboard, Microsoft Wireless Multimedia Keyboard 1.0A, Northgate OmniKey 101, OLPC, Ortek MCK-800 MM/Internet keyboard, PC-98xx Series, Propeller Voyager (KTEZ-1000), QTronix Scorpius 98N+, Samsung SDM 4500P, Samsung SDM 4510P, Sanwa Supply SKB-KG3, SILVERCREST Multimedia Wireless Keyboard, SK-1300, SK-2500, SK-6200, SK-7100, Sun Type 4, Sun Type 5, Sun Type 6 (Japanese layout), Sun Type 6/7 USB, Sun Type 6/7 USB (European layout), Sun Type 6 USB (Japanese layout), Sun Type 6 USB (Unix layout), Sun Type 7 USB, Sun Type 7 USB (European layout), Sun Type 7 USB (Japanese layout) / Japanese 106-key, Sun Type 7 USB (Unix layout), Super Power Multimedia Keyboard, SVEN Ergonomic 2500, SVEN Slim 303, Symplon PaceBook (tablet PC), Targa Visionary 811, Toshiba Satellite S3000, Truly Ergonomic Computer Keyboard Model 227 (Wide Alt keys), Truly Ergonomic Computer Keyboard Model 229 (Standard sized Alt keys\, additional Super and Menu key), Trust Direct Access Keyboard, Trust Slimline, Trust Wireless Keyboard Classic, TypeMatrix EZ-Reach 2020, TypeMatrix EZ-Reach 2030 PS2, TypeMatrix EZ-Reach 2030 USB, TypeMatrix EZ-Reach 2030 USB (102/105:EU mode), TypeMatrix EZ-Reach 2030 USB (106:JP mode), Unitek KB-1925, ViewSonic KU-306 Internet Keyboard, Winbook Model XP5, Yahoo! Internet Keyboard
d-i	keyboard-configuration/model	select	Do not configure keyboard; keep kernel keymap
keyboard-configuration	keyboard-configuration/model	select	Do not configure keyboard; keep kernel keymap
d-i	keyboard-configuration/compose	select	No compose key
keyboard-configuration	keyboard-configuration/compose	select	No compose key
d-i	keyboard-configuration/modelcode	string	SKIP
keyboard-configuration	keyboard-configuration/modelcode	string	SKIP
d-i	keyboard-configuration/switch	select	No temporary switch
keyboard-configuration	keyboard-configuration/switch	select	No temporary switch
d-i	keyboard-configuration/optionscode	string	
keyboard-configuration	keyboard-configuration/optionscode	string	
# Country of origin for the keyboard:
d-i	keyboard-configuration/layout	select	Germany
keyboard-configuration	keyboard-configuration/layout	select	Germany
d-i	keyboard-configuration/layoutcode	string	
keyboard-configuration	keyboard-configuration/layoutcode	string	
# Keep the current keyboard layout in the configuration file?
d-i	keyboard-configuration/unsupported_config_layout	boolean	true
keyboard-configuration	keyboard-configuration/unsupported_config_layout	boolean	true
# Detect keyboard layout?
keyboard-configuration	console-setup/ask_detect	boolean	false
d-i	keyboard-configuration/store_defaults_in_debconf_db	boolean	true
keyboard-configuration	keyboard-configuration/store_defaults_in_debconf_db	boolean	true
vagrant@linus-kitchen:~$ 
```

However I can't find "kbd-chooser" in there:
```
vagrant@linus-kitchen:~$ sudo debconf-get-selections | grep chooser
vagrant@linus-kitchen:~$ 
```

Also, the `/etc/default/keyboard` file does not reflect the variant and layout values:
```
vagrant@linus-kitchen:~$ cat /etc/default/keyboard 
# KEYBOARD CONFIGURATION FILE

# Consult the keyboard(5) manual page.

XKBMODEL="SKIP"
XKBLAYOUT=""
XKBVARIANT=""
XKBOPTIONS=""

BACKSPACE="guess"
```

@neilkidd any ideas what's wrong here?

**Comment by tknerr** [comment]
Maybe the `keyboard-configuration/xkb-keymap` boot parameter is missing?

See https://help.ubuntu.com/lts/installation-guide/armhf/apbs04.html

(note: it's the ubuntu1604-desktop box I tested with)

**Comment by tknerr** [comment]
tried with the additional `keyboard-configuration/xkb-keymap=de` boot parameter.

It ended up correctly in the debconf selections...
```
vagrant@linus-kitchen:~$ sudo debconf-get-selections | grep xkb
d-i	keyboard-configuration/xkb-keymap	select	de
keyboard-configuration	keyboard-configuration/xkb-keymap	select	de
```

...but still, keyboard has US layout after logging in to the VM :-/

I'm lost...

**Comment by inetbiz** [comment]
Line 222:  You might consider #102

**Pull request closed without merging**
