### PR TITLE
bump version - 16.04.2

### PR DESCRIPTION
**Pull request by rexut**
On 2017-02-17 the new pointrelease 2 was released.

### CODE REVIEW

**Comment by oinume** [comment]
Hi @annawake,
Could you merge this PR?

**Comment by matthijsbos** [comment]
Verified working

**Comment by tknerr** [comment]
FYI - if anyone still wants to access the old 16.04.1 iso images they are available here:
http://old-releases.ubuntu.com/releases/xenial/

**Comment by tknerr** [comment]
@rexut the link names in the README should probably be updated as well -- they still refer to the 16.04.1 boxes:

image

**Comment by tknerr** [comment]
👍

**Comment by DieterReuter** [comment]
This PR is outdated and should be closed, we're at 16.04.3 now.

**Pull request closed without merging**
