### PR TITLE
Fixing issues with SSH_USERNAME and SSH_PASSWORD

### PR DESCRIPTION
**Pull request by kamino**
if SSH_USERNAME and SSH_PASSWORD are set to different values that
vagrant/vagrant, the image could not be built because of ssh authentication
errors.

### CODE REVIEW

**Comment by rasa** [comment]
Great stuff! LGTM.

**Comment by annawake** [comment]
Does not work - breaks all the docker images and strangely Ubuntu 14.04.  Backing this change out.  The images will build, but vagrant will not be able to ssh in.  Very strange.

**Comment by kamino** [comment]
@annawake hum, I'll dig into it as soon as I have time in the next few week. Thanks for the feedback.

**Comment by annawake** [comment]
Sorted it out - had to do with the removal of the linux headers - it has been repushed and seems to work with a test build.  Waiting for the full build to run to get the final verdict.

**Comment by annawake** [comment]
Tests fine, released

**Pull request merged**
