### PR TITLE
Adding Ansible as CM tool (issue #7)

### PR DESCRIPTION
**Pull request by joaocc**
boxcutter/ubuntu#7

### CODE REVIEW

**Comment by rasa** [comment]
LGTM. @misheska?

**Comment by mathewpeterson** [comment]
Is there anything I can help out to get this merged?

**Comment by becw** [comment]
This PR also needs to add an 'ansible' case and call the `install_ansible()` function.

**Comment by rasa** [comment]
@becw: good point. @mathewpeterson ?

**Comment by joaocc** [comment]
creating new pull request with the suggested change

**Comment by mathewpeterson** [comment]
@becw Is this what you are looking for?

**Comment by becw** [comment]
Yes, that code looks good to me.

**Comment by mathewpeterson** [comment]
I was able to successfully build the machine.

**Pull request merged**
