### PR TITLE
One template to rule them all again 😊

### PR DESCRIPTION
**Pull request by dusek**
I thought it is unfortunate that the ubuntu.json main template is no longer used for 1510 and 1604, adding duplication to code (and friction when having to add the same stuff to 3 template files instead of 1).

So I decided to give it a try to generalize the ubuntu.json template to allow for modifications needed for 1510 and 1604.

In the process I unified the `boot_command` for vmware, virtualbox and parallels. That is how it was before this PR in ubuntu1604.json and ubuntu1510.json, so I figured it is worth giving it a try also for the main template. I don't understand the original motivation for different `boot_command` between parallels, vmware and virtualbox, so please consider that (and in this sense also please treat this PR as a bit of a RFC).

Tested on:
- OS X 10.11.4
- packer 0.10.0

Tested with:
- `bin/box build ubuntu1204 virtualbox`
- `bin/box build ubuntu1204 vmware`
- `bin/box build ubuntu1404 virtualbox`
- `bin/box build ubuntu1404 vmware`
- `bin/box build ubuntu1604 virtualbox`
- `bin/box build ubuntu1604 vmware`
- `bin/box build ubuntu1510 virtualbox`

For the virtualbox ones, I also did `bin/ssh-box …` just to see the resulting boxes can be booted and ssh’ed in.

### CODE REVIEW

**Comment by dusek** [comment]
I updated the last commit to reflect the just merged #55.

**Comment by rickard-von-essen** [comment]
Nice, I'll see if I can test this on Parallels later today.

**Comment by dusek** [comment]
@annawake please is there anything (even if trivial) I (we) could test on the build VMs after such change, apart from testing that `bin/box build ubuntu1404.json virtualbox` followed by `bin/box ssh ubuntu1404.json virtualbox` both work (finish and do not error out)?

**Comment by dusek** [comment]
I guess this has been basically merged now (which is great), so closing.

**Comment by dusek** [comment]
Some changes did not make it to master – the one dealing with the `locale.sh` script at least.

**Comment by annawake** [comment]
Addressed by https://github.com/boxcutter/ubuntu/commit/d19fd87442a82f87da9d6894af9b52a10c680418

**Pull request closed without merging**
